require(game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game).caption("doors nightmare mode loaded by Zeca140xx Version V3.5",true)
 wait(6)
require(game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game).caption("credits: zeca140xx, SESON KC[candle script], Hungered,",true)
 wait(6)
require(game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game).caption("join discord [https://discord.gg/M7Dr8cyU] where are the scripts and mods",true)
 wait(6)
require(game.Players.LocalPlayer.PlayerGui.MainUI.Initiator.Main_Game).caption("Loading floor 2 and good luck",true)
 wait(3)
